name: Build

on: push

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows-static
    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: lukka/get-cmake@latest
      - name: dir
        run: find $RUNNER_WORKSPACE
        shell: bash

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgJsonGlob: '**/vcpkg.json'

      - name: List $RUNNER_WORKSPACE before build
        run: find $RUNNER_WORKSPACE
        shell: bash
      - name: Prints output of run-vcpkg's action.
        run: echo "root='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}', triplet='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_DEFAULT_TRIPLET_OUT }}' "
      - name: Run CMake ($BUILD_TYPE configuration)
        uses: lukka/run-cmake@v10
        id: runcmake
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: 'ninja-multi-vcpkg'
          buildPreset: 'ninja-vcpkg-release'
          buildPresetAdditionalArgs: '[`--config Release`]'
      - name: List $RUNNER_WORKSPACE after build
        run: find $RUNNER_WORKSPACE
        shell: bash
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: stockmq-quik-connector
          path: |
            integration/lib/**/Release/StockMQ.dll
            integration/src/*.lua
            integration/*.lua
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: stockmq-quik-examples
          path: |
            examples
      - name: Download artifact (stockmq-quik-connector)
        uses: actions/download-artifact@v4
        with:
          name: stockmq-quik-connector
      - name: Download artifact (stockmq-quik-examples)
        uses: actions/download-artifact@v4
        with:
          name: stockmq-quik-examples
      - name: Display structure of downloaded files
        run: ls -R
        shell: bash
      - name: Archive Release (stockmq-quik-connector)
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: zip
          path: stockmq-quik-connector
          filename: stockmq-quik-connector.zip
      - name: Archive Release (stockmq-quik-examples)
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: zip
          path: stockmq-quik-examples
          filename: stockmq-quik-examples.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            stockmq-quik-connector.zip
            stockmq-quik-examples.zip

